version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=mydb
    ports:
    - 5432:5432
    volumes:
    - /tmp/my_dbdata_postgres:/var/lib/postgres
    networks:
    - generator

networks:
  generator:
    

 
